version: '3'

services:
  api:
    build: ./api
    depends_on:
      - db
    links:
      - db
    ports:
       - 3000:3000
    volumes:
      - ./api:/go/src/github.com/VampiretheEndlessNight/entrails/api
  db:
    build: ./mysql
    ports:
        - 3306:3306
    volumes:
        - /var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: entrails
        MYSQL_USER: admin
        MYSQL_PASSWORD: password