version: '3'

services:
  api:
    build: ./api
    depends_on:
      - db
    command: ./tmp/wait-for-it.sh, db:3306, --
    links:
      - db
    ports:
       - 3000:3000
    volumes:
      - ./api:/go/src/github.com/VampiretheEndlessNight/entrails/api
  db:
    build: ./mysql
    ports:
        - 3306:3306
    volumes:
        - db_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: entrails
volumes:
  db_data: