version: '3'

services:
  api:
    build: ./api
    depends_on:
      - mysql
    links:
      - mysql
    ports:
       - 3000:3000
    volumes:
      - ./api:/go/src/github.com/VampiretheEndlessNight/entrails/api
  mysql:
    build: ./mysql
    expose:
        - 3306
    volumes:
        - database_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: entrails
        MYSQL_USER: admin
        MYSQL_PASSWORD: password

volumes:
  database_data: {}