version: '2'
services:
  web:
    build: .
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6.26
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=database
    ports:
      - "3306:3306"