-- MySQL Script generated by MySQL Workbench
-- Tue 04 Apr 2017 11:53:07 AM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema entrails
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema entrails
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `entrails` DEFAULT CHARACTER SET utf8 ;
USE `entrails` ;

-- -----------------------------------------------------
-- Table `entrails`.`ages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`ages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `vitae` INT NOT NULL,
  `prestige` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `vitae_UNIQUE` (`vitae` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`paths`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`paths` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`players` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `age_id` INT NOT NULL,
  `paths_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_players_ages_age_id` (`age_id` ASC),
  INDEX `fk_players_paths_path_id` (`paths_id` ASC),
  CONSTRAINT `fk_players_ages_age_id`
    FOREIGN KEY (`age_id`)
    REFERENCES `entrails`.`ages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_paths_path_id`
    FOREIGN KEY (`paths_id`)
    REFERENCES `entrails`.`paths` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`clans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`clans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `weakness` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`backgrounds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`backgrounds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` MEDIUMTEXT NOT NULL,
  `level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`disciplines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`disciplines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `clan_id` INT NOT NULL,
  PRIMARY KEY (`id`, `clan_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_disciplines_clans_clan_id` (`clan_id` ASC),
  CONSTRAINT `fk_disciplines_clans_clan_id`
    FOREIGN KEY (`clan_id`)
    REFERENCES `entrails`.`clans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`powers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`powers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `level` ENUM('basic', 'intermediate', 'advanced') NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `disciplines_id` INT NOT NULL,
  PRIMARY KEY (`id`, `disciplines_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_powers_disciplines1_idx` (`disciplines_id` ASC),
  CONSTRAINT `fk_powers_disciplines_discipline_id`
    FOREIGN KEY (`disciplines_id`)
    REFERENCES `entrails`.`disciplines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`player_disciplines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`player_disciplines` (
  `player_id` INT NOT NULL,
  `powers_id` INT NOT NULL,
  INDEX `fk_player_assets_players1_idx` (`player_id` ASC),
  PRIMARY KEY (`powers_id`),
  CONSTRAINT `fk_player_disciplines_players_player_id`
    FOREIGN KEY (`player_id`)
    REFERENCES `entrails`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_disciplines_powers`
    FOREIGN KEY (`powers_id`)
    REFERENCES `entrails`.`powers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`influences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`influences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`unlocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`unlocks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `age_id` INT NOT NULL,
  PRIMARY KEY (`id`, `age_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_unlocks_ages_age_id` (`age_id` ASC),
  CONSTRAINT `fk_unlocks_ages_age_id`
    FOREIGN KEY (`age_id`)
    REFERENCES `entrails`.`ages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` MEDIUMTEXT NOT NULL,
  `cost` ENUM('0', '1', '3', '6', 'overflow') NOT NULL,
  `path_id` INT NOT NULL,
  PRIMARY KEY (`id`, `path_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_path_skills_path_id` (`path_id` ASC),
  CONSTRAINT `fk_skills_paths_path_id`
    FOREIGN KEY (`path_id`)
    REFERENCES `entrails`.`paths` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`player_clans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`player_clans` (
  `clans_id` INT NOT NULL,
  `players_id` INT NOT NULL,
  `heritage` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`clans_id`, `players_id`),
  INDEX `fk_clans_has_players_players1_idx` (`players_id` ASC),
  INDEX `fk_clans_has_players_clans1_idx` (`clans_id` ASC),
  CONSTRAINT `fk_player_clans_has_players_clans1`
    FOREIGN KEY (`clans_id`)
    REFERENCES `entrails`.`clans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clans_has_players_players1`
    FOREIGN KEY (`players_id`)
    REFERENCES `entrails`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`player_influences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`player_influences` (
  `influence_id` INT NOT NULL,
  `last_used` TIMESTAMP NULL DEFAULT NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`influence_id`, `player_id`),
  INDEX `fk_player_influences_influences_influence_id` (`influence_id` ASC),
  INDEX `fk_player_influences_players_player_id` (`player_id` ASC),
  CONSTRAINT `fk_player_influences_influences_influence_id`
    FOREIGN KEY (`influence_id`)
    REFERENCES `entrails`.`influences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_influences_players_player_id`
    FOREIGN KEY (`player_id`)
    REFERENCES `entrails`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entrails`.`player_backgrounds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entrails`.`player_backgrounds` (
  `players_id` INT NOT NULL,
  `backgrounds_id` INT NOT NULL,
  `last_used` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`players_id`, `backgrounds_id`),
  INDEX `fk_players_has_backgrounds_backgrounds1_idx` (`backgrounds_id` ASC),
  CONSTRAINT `fk_player_backgrounds_players_player_id`
    FOREIGN KEY (`players_id`)
    REFERENCES `entrails`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_backgrounds_backgrounds_background_id`
    FOREIGN KEY (`backgrounds_id`)
    REFERENCES `entrails`.`backgrounds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
