-- MySQL Script generated by MySQL Workbench
-- Fri 11 Nov 2016 01:47:25 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `vitae` INT NOT NULL,
  `prestige` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `vitae_UNIQUE` (`vitae` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paths`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paths` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`players` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `age_id` INT NOT NULL,
  `paths_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Players_Ages_idx` (`age_id` ASC),
  INDEX `fk_players_paths1_idx` (`paths_id` ASC),
  CONSTRAINT `fk_player_age`
    FOREIGN KEY (`age_id`)
    REFERENCES `mydb`.`ages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_path`
    FOREIGN KEY (`paths_id`)
    REFERENCES `mydb`.`paths` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `weakness` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`backgrounds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`backgrounds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` MEDIUMTEXT NOT NULL,
  `level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`discipline_names`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`discipline_names` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `clan_id` INT NOT NULL,
  PRIMARY KEY (`id`, `clan_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_disciplines_clans1_idx` (`clan_id` ASC),
  CONSTRAINT `fk_disciplines_clans1`
    FOREIGN KEY (`clan_id`)
    REFERENCES `mydb`.`clans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` MEDIUMTEXT NOT NULL,
  `discipline_id` INT NOT NULL,
  `level` ENUM('basic', 'intermediate', 'advanced') NOT NULL,
  PRIMARY KEY (`id`, `discipline_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_discipline_dots_disciplines1_idx` (`discipline_id` ASC),
  CONSTRAINT `fk_discipline_dots_disciplines1`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `mydb`.`discipline_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player_disciplines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player_disciplines` (
  `player_id` INT NOT NULL,
  `discipline_level_id` INT NOT NULL,
  `discipline_id` INT NOT NULL,
  INDEX `fk_player_assets_players1_idx` (`player_id` ASC),
  PRIMARY KEY (`discipline_level_id`, `discipline_id`),
  CONSTRAINT `fk_player_assets_players1`
    FOREIGN KEY (`player_id`)
    REFERENCES `mydb`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_assets_discipline_levels1`
    FOREIGN KEY (`discipline_level_id` , `discipline_id`)
    REFERENCES `mydb`.`disciplines` (`id` , `discipline_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`influences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`influences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`age_unlocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`age_unlocks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `age_id` INT NOT NULL,
  PRIMARY KEY (`id`, `age_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_age_unlocks_ages1_idx` (`age_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mydb`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` MEDIUMTEXT NOT NULL,
  `cost` ENUM('0', '1', '3', '6', 'overflow') NOT NULL,
  `path_id` INT NOT NULL,
  PRIMARY KEY (`id`, `path_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_path_skills_paths1_idx` (`path_id` ASC),
  CONSTRAINT `fk_skills_path`
    FOREIGN KEY (`path_id`)
    REFERENCES `mydb`.`paths` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player_clans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player_clans` (
  `clans_id` INT NOT NULL,
  `players_id` INT NOT NULL,
  `heritage` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`clans_id`, `players_id`),
  INDEX `fk_clans_has_players_players1_idx` (`players_id` ASC),
  INDEX `fk_clans_has_players_clans1_idx` (`clans_id` ASC),
  CONSTRAINT `fk_clans_has_players_clans1`
    FOREIGN KEY (`clans_id`)
    REFERENCES `mydb`.`clans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clans_has_players_players1`
    FOREIGN KEY (`players_id`)
    REFERENCES `mydb`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player_influences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player_influences` (
  `influences_id` INT NOT NULL,
  `last_used` TIMESTAMP NOT NULL DEFAULT 0,
  PRIMARY KEY (`influences_id`),
  INDEX `fk_player_influences_id` (`influences_id` ASC),
  CONSTRAINT `fk_players_has_influences_influences`
    FOREIGN KEY (`influences_id`)
    REFERENCES `mydb`.`influences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player_backgrounds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player_backgrounds` (
  `players_id` INT NOT NULL,
  `players_age_id` INT NOT NULL,
  `backgrounds_id` INT NOT NULL,
  `last_used` TIMESTAMP NOT NULL DEFAULT 0,
  PRIMARY KEY (`players_id`, `players_age_id`, `backgrounds_id`),
  INDEX `fk_players_has_backgrounds_backgrounds1_idx` (`backgrounds_id` ASC),
  INDEX `fk_players_has_backgrounds_players1_idx` (`players_id` ASC, `players_age_id` ASC),
  CONSTRAINT `fk_players_has_backgrounds_players1`
    FOREIGN KEY (`players_id` , `players_age_id`)
    REFERENCES `mydb`.`players` (`id` , `age_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_has_backgrounds_backgrounds1`
    FOREIGN KEY (`backgrounds_id`)
    REFERENCES `mydb`.`backgrounds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
